import test from 'node:test';
import assert from 'node:assert/strict';
import {participantFile,sessionFile,parseTransfer,mergeParticipants,sessionCode} from '../dist/transfer.js';
import {exportParticipants} from '../dist/reporting.js';
const state={id:'abc-123',name:'Émilie',code:'ATELIER-123',local:true,secret:'secret-interdit',answers:{Q1:'B',S1:'Je vérifie.\nSans cliquer.',goal:'=formule',devices:['Ordinateur']},revision:4,finished:true};
const roundtrip=x=>parseTransfer(JSON.stringify(x));
test('Un vrai parcours devient un fichier importable sans secret ni compte',()=>{const file=participantFile(state);assert.ok(!JSON.stringify(file).includes(state.secret));const parsed=roundtrip(file);assert.equal(parsed.code,state.code);assert.equal(parsed.participants[0].answers.S1,state.answers.S1);assert.equal(parsed.participants[0].finished,true);});
test('Import, observations, sauvegarde et restauration conservent les données et le CSV',()=>{let ps=roundtrip(participantFile(state)).participants;ps[0].observations={D1_open:'3',S1:'P',note:'Réponse orale'};const session={id:'session-1',title:'Vendredi',code:state.code};const restored=roundtrip(sessionFile(session,ps)).participants;assert.deepEqual(restored,ps);assert.equal(exportParticipants(session,ps),exportParticipants(session,restored));});
test('Réimporter actualise les réponses sans doubler ni perdre les observations',()=>{const old=roundtrip(participantFile(state)).participants;old[0].observations={D1_open:'2',note:'À reprendre'};const fresh=roundtrip(participantFile({...state,revision:5,answers:{Q1:'NSP'}})).participants;const result=mergeParticipants(old,fresh);assert.equal(result.participants.length,1);assert.equal(result.updated,1);assert.equal(result.participants[0].answers.Q1,'NSP');assert.deepEqual(result.participants[0].observations,old[0].observations);assert.equal(old[0].answers.Q1,'B');});
test('Un ancien fichier ne remplace pas une réponse plus récente',()=>{const old=roundtrip(participantFile(state)).participants;const recent=roundtrip(participantFile({...state,revision:8})).participants;assert.equal(mergeParticipants(recent,old).ignored,1);assert.equal(mergeParticipants(recent,old).participants[0].revision,8);});
test('Deux personnes de même prénom restent distinctes',()=>{const a=roundtrip(participantFile(state)).participants;const b=roundtrip(participantFile({...state,id:'xyz-456'})).participants;assert.equal(mergeParticipants(a,b).participants.length,2);});
test('Les essais, fichiers cassés, versions inconnues et codes incohérents sont refusés',()=>{assert.throws(()=>participantFile({...state,demo:true}));assert.throws(()=>parseTransfer('{'));assert.throws(()=>roundtrip({version:42}));const file=participantFile(state);file.participant.code='AUTRE';assert.throws(()=>roundtrip(file));assert.throws(()=>sessionCode('<script>'));assert.equal(sessionCode(' atelier-123 '),state.code);});
test('Les observations injectées dans un résultat participant ne sont pas acceptées',()=>{const file=participantFile(state);file.participant.observations={D1_open:'3'};assert.deepEqual(roundtrip(file).participants[0].observations,{});});

test('Le parcours sans code est affecté au groupe choisi sans modifier le fichier source',async()=>{const {FREE_SESSION_CODE,assignToSession}=await import('../dist/transfer.js');const parsed=roundtrip(participantFile({...state,code:FREE_SESSION_CODE}));const assigned=assignToSession(parsed,'ATELIER-CIBLE');assert.equal(assigned[0].code,'ATELIER-CIBLE');assert.equal(parsed.participants[0].code,FREE_SESSION_CODE);assert.equal(assigned[0].answers.S1,state.answers.S1);assert.throws(()=>assignToSession(roundtrip(participantFile(state)),'AUTRE-GROUPE'));});
